; Project: OpenHeading-IX
; PlatformIO configuration placeholder
;
; The initial P0 code is Arduino-style and can also be compiled in Arduino IDE.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
